Fix github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,20 +43,21 @@ jobs:
         run: |
           retries=5
           while [ $retries -gt 0 ]; do
-            curl --output /dev/null --silent --head --fail http://localhost:80
-            retVal=$?
-            if [ $retVal -eq 0 ]; then
+            if curl --output /dev/null --silent --head --fail http://localhost:80; then
               echo "Service is up!"
               break
+            else
+              retVal=$?
+              echo "Attempt $((6 - retries)) failed with error code $retVal. Retrying..."
+              retries=$((retries - 1))
+              sleep 30
             fi
-            echo "Waiting for the service to be up, attempt $((6 - retries))..."
-            retries=$((retries - 1))
-            sleep 15
           done
           if [ $retries -eq 0 ]; then
             echo "Service did not become ready in time"
             exit 1
           fi
+
       -
         name: Run tests
         run: docker compose exec -T php composer run-script test-all
